# Docker Compose file for deploying Loki, Prometheus, and Grafana on the monitoring server

version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  loki-data:

services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring
    labels:
      - "environment=production"

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ginger
    networks:
      - monitoring
    labels:
      - "environment=production"

  loki:
    image: grafana/loki:2.9.10
    container_name: loki
    restart: unless-stopped
    volumes:
      - loki-data:/loki
      - ./loki/config-loki.yml:/etc/loki/config-loki.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/config-loki.yml
    networks:
      - monitoring
    labels:
      - "environment=production"


  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
    networks:
      - monitoring
    labels:
      - "environment=production"

## Will update this code soon.
  cadvisor:
    # TODO: latest tag is not updated, check latest release https://github.com/google/cadvisor/releases 
    image: gcr.io/cadvisor/cadvisor:v0.45.0     
    container_name: cadvisor
    ports:
       - "8080:8080"
   # network_mode: host
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true